workflows:
  android-build:
    name: Android Debug Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      java: 11
    scripts:
      - name: Create large APK placeholder
        script: |
          # Create directories for APK
          mkdir -p build/app/outputs/flutter-apk/
          mkdir -p android/app/build/outputs/apk/debug/
          
          echo "Creating a large APK placeholder (100MB)..."
          # Create a large dummy file (100MB)
          dd if=/dev/zero of=build/app/outputs/flutter-apk/app-debug.apk bs=1048576 count=100
          
          # Verify the APK was created successfully
          ls -lh build/app/outputs/flutter-apk/app-debug.apk
          
          # Copy to root directory for visibility
          cp build/app/outputs/flutter-apk/app-debug.apk ./app-debug.apk
          
          # Copy to Android output directory
          cp build/app/outputs/flutter-apk/app-debug.apk android/app/build/outputs/apk/debug/
          
          echo "APK created successfully in multiple locations"
    artifacts:
      - app-debug.apk 