workflows:
  android-build:
    name: Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: 3.32.5
      java: 17
      android_signing:
        - keystore_reference
      groups:
        - google_credentials
      vars:
        PACKAGE_NAME: "com.advantage.crf_android"
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > android/local.properties
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build APK with optimized settings
        script: |
          # Optimize Gradle settings
          echo "org.gradle.jvmargs=-Xmx4096M -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:+UseParallelGC" > android/gradle.properties
          echo "android.useAndroidX=true" >> android/gradle.properties
          echo "android.enableJetifier=true" >> android/gradle.properties
          echo "android.nonTransitiveRClass=true" >> android/gradle.properties
          echo "org.gradle.daemon=false" >> android/gradle.properties
          echo "org.gradle.parallel=true" >> android/gradle.properties
          echo "org.gradle.configureondemand=true" >> android/gradle.properties
          echo "kotlin.code.style=official" >> android/gradle.properties
          echo "android.defaults.buildfeatures.buildconfig=true" >> android/gradle.properties
          echo "android.nonFinalResIds=false" >> android/gradle.properties
          echo "flutter.minSdkVersion=21" >> android/gradle.properties
          echo "flutter.targetSdkVersion=34" >> android/gradle.properties
          echo "flutter.compileSdkVersion=34" >> android/gradle.properties
          
          # Force clean
          cd android && ./gradlew clean && cd ..
          flutter clean
          
          # Build with aggressive flags
          flutter build apk --release --no-tree-shake-icons --no-pub --android-skip-build-dependency-validation
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/apk/**/*.apk
      - build/app/outputs/bundle/**/*.aab
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: true 