workflows:
  android-build:
    name: Android Debug Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: 3.16.9  # Use older Flutter version that's more compatible with plugins
      java: 17
    scripts:
      - name: Build with older Flutter version
        script: |
          # Create local.properties
          echo "flutter.sdk=$HOME/programs/flutter" > android/local.properties
          
          # Get dependencies
          flutter pub get
          
          # Clean the project
          flutter clean
          
          # Build debug APK with older Flutter version
          flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk 